import React from 'react';
import { ArrowLeft, CheckCircle2, AlertTriangle, ShieldCheck, ArrowRight, Calendar } from 'lucide-react';
import type { View, WellbeingAssessment } from '../types/wellbeing';

interface AssessmentResultPageProps {
  assessment: WellbeingAssessment | null;
  navigate: (view: View) => void;
}

export const AssessmentResultPage: React.FC<AssessmentResultPageProps> = ({
  assessment,
  navigate,
}) => {
  if (!assessment) {
    return (
      <div className="mx-auto max-w-xl px-5 py-12 text-center">
        <h2 className="text-xl font-semibold text-[#1e3c35]">No assessment found</h2>
        <p className="mt-2 text-sm text-[#78908a]">Please submit a check-in first to generate a risk analysis.</p>
        <button
          onClick={() => navigate('checkin')}
          className="mt-6 rounded-xl bg-[#2f6f64] px-5 py-3 text-sm font-semibold text-white"
        >
          Go to Check-in
        </button>
      </div>
    );
  }

  const { risk_level, risk_score, contributing_factors, recommendations, explanation } = assessment;

  const levelMeta = {
    low: {
      badge: 'Low Wellbeing Risk',
      title: 'Your routine patterns look steady.',
      color: 'bg-[#eaf4ef] text-[#2f6f64] border-[#b8dbc9]',
      accent: '#2f6f64',
    },
    moderate: {
      badge: 'Moderate Wellbeing Risk',
      title: 'Your current responses indicate moderate wellbeing risk.',
      color: 'bg-[#fff4df] text-[#9a6b3c] border-[#f3d3a7]',
      accent: '#b8834e',
    },
    high: {
      badge: 'Increased Wellbeing Risk',
      title: 'Your current responses indicate increased wellbeing risk.',
      color: 'bg-[#f8eee4] text-[#936744] border-[#e7c6af]',
      accent: '#936744',
    },
  }[risk_level] || {
    badge: 'Wellbeing Indicator',
    title: 'Your current responses indicate routine changes.',
    color: 'bg-[#eaf4ef] text-[#2f6f64] border-[#b8dbc9]',
    accent: '#2f6f64',
  };

  return (
    <div className="mx-auto max-w-4xl px-5 py-8 sm:px-8 lg:py-12">
      <button
        onClick={() => navigate('dashboard')}
        className="mb-6 inline-flex items-center gap-1.5 text-xs font-medium text-[#78908a] hover:text-[#2f6f64]"
      >
        <ArrowLeft size={14} /> Back to dashboard
      </button>

      <div className="mb-8">
        <p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-[#a47b54]">
          Assessment Result
        </p>
        <h1 className="text-3xl font-semibold tracking-[-0.035em] text-[#1e3c35] sm:text-4xl">
          Wellbeing Pattern Summary
        </h1>
        <p className="mt-2 text-sm text-[#718983]">
          Generated by FastAPI based on your recent check-in inputs.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
        {/* Risk Score & Level Card */}
        <div className="rounded-2xl border border-[#dce9e4] bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between">
            <span className={`rounded-full border px-3 py-1 text-xs font-semibold ${levelMeta.color}`}>
              {levelMeta.badge}
            </span>
            <span className="text-xs text-[#869b95]">Indicator Score</span>
          </div>

          <div className="mt-6 flex items-end gap-3">
            <span className="text-5xl font-semibold tracking-tight text-[#1e3c35]">{risk_score}</span>
            <span className="mb-2 text-sm text-[#869b95]">/ 100 pattern index</span>
          </div>

          <p className="mt-4 text-base font-semibold text-[#2b5046]">{levelMeta.title}</p>
          <p className="mt-1 text-sm leading-6 text-[#6e8780]">{explanation}</p>

          <div className="mt-6 border-t border-[#edf2ef] pt-4 flex items-center gap-2 text-xs text-[#90a29c]">
            <ShieldCheck size={16} className="text-[#2f6f64] shrink-0" />
            This is an early-warning pattern indicator, not a medical or clinical burnout diagnosis.
          </div>
        </div>

        {/* Next Check-in Timing Card */}
        <div className="rounded-2xl border border-[#e4ebe8] bg-[#f5faf7] p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-[#48675f]">
              <Calendar size={16} /> When to check in next
            </div>
            <h3 className="mt-3 text-lg font-semibold text-[#1e3c35]">Tomorrow evening</h3>
            <p className="mt-2 text-sm leading-6 text-[#66807a]">
              Checking in regularly once a day helps maintain an accurate personal baseline and provides more tailored nudges.
            </p>
          </div>

          <div className="mt-6 flex flex-col gap-2">
            <button
              onClick={() => navigate('nudges')}
              className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#2f6f64] px-4 py-3 text-sm font-semibold text-white hover:bg-[#245e54]"
            >
              View Recommendations <ArrowRight size={15} />
            </button>
            <button
              onClick={() => navigate('dashboard')}
              className="w-full rounded-xl border border-[#dce9e4] bg-white px-4 py-2.5 text-sm font-semibold text-[#52736a] hover:bg-[#f1f6f3]"
            >
              Return to Dashboard
            </button>
          </div>
        </div>
      </div>

      <div className="mt-6 grid gap-6 sm:grid-cols-2">
        {/* Contributing Factors */}
        <div className="rounded-2xl border border-[#e4ebe8] bg-white p-6">
          <h3 className="flex items-center gap-2 text-base font-semibold text-[#35584f]">
            <AlertTriangle size={18} className="text-[#b8834e]" />
            Key Contributing Factors
          </h3>
          {contributing_factors && contributing_factors.length > 0 ? (
            <ul className="mt-4 flex flex-col gap-3">
              {contributing_factors.map((factor, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-[#6e8780]">
                  <span className="mt-1 size-1.5 shrink-0 rounded-full bg-[#b8834e]" />
                  {factor}
                </li>
              ))}
            </ul>
          ) : (
            <p className="mt-4 text-sm text-[#8aa099]">No high-variance stress factors identified in recent check-in.</p>
          )}
        </div>

        {/* Recommended Actions */}
        <div className="rounded-2xl border border-[#e4ebe8] bg-white p-6">
          <h3 className="flex items-center gap-2 text-base font-semibold text-[#35584f]">
            <CheckCircle2 size={18} className="text-[#2f6f64]" />
            Recommended Supportive Actions
          </h3>
          {recommendations && recommendations.length > 0 ? (
            <ul className="mt-4 flex flex-col gap-3">
              {recommendations.map((action, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-[#6e8780]">
                  <span className="mt-1 size-1.5 shrink-0 rounded-full bg-[#2f6f64]" />
                  {action}
                </li>
              ))}
            </ul>
          ) : (
            <p className="mt-4 text-sm text-[#8aa099]">Continue your regular healthy routine.</p>
          )}
        </div>
      </div>
    </div>
  );
};
